source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
gem 'devise', '~> 1.4.6'
gem 'unicorn'
gem 'haml'
#TODO: really need compass? 
# compass sass css framework
gem 'compass', '>= 0.11.6'
#gem 'kaltura-ruby'
gem 'kaltura'
gem 'whenever'
gem 'rake'
gem 'minitest'
# Deploy with Capistrano
 gem 'capistrano'

#gem sources -a http://gems.github.com
gem "thoughtbot-paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
#rackspace cloud files
#gem 'cloudfiles'
#gem 'cocaine' #a dependency that paperclilp didn't pick up yet
#gem 'paperclip-cloudfiles', :require => 'thoughtbot-paperclip'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

# devise auth
