source "http://rubygems.org"

gem "rails", "3.2.1"
gem "sass-rails", "~> 3.2.3"
gem "coffee-rails", "3.2.1"
gem 'uglifier', ">= 1.0.3"

gem 'heroku'

gem 'json'

gem "devise"
gem "devise-encryptable"
gem "omniauth-facebook"
gem "omniauth-twitter"

gem "kaminari"
gem "carrierwave"
gem "jquery-rails"
gem "meta_search"

gem "dynamic_form"
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'client_side_validations'

#attempt to restrain bot requests, esp. on user data reset requests
gem "rack-throttle"

gem "acts-as-taggable-on", :git => "git://github.com/mbleigh/acts-as-taggable-on.git", :branch => "master"
gem "rails3-jquery-autocomplete"

gem "cloudfiles"
gem "paperclip", ">= 3.1.4"

gem "paperclip-cloudfiles"

#gem sources -a http://gems.github.com
#gem "thoughtbot-paperclip", :git => "git://github.com/thoughtbot/paperclip.git"

gem "nokogiri", ">= 1.5.5"

gem "delayed_job_active_record"
gem "daemons"
gem 'will_paginate', '~> 3.0'
#snazzy forUmz!
gem 'forum_monster'

group :test, :development do
  gem "rspec-rails"
  gem "spork", "~> 1.0.0rc1"
  gem "ruby-debug19"
  gem "awesome_print"
	gem "sqlite3"
	gem "mailcatcher"
	gem "rails3-generators"
	gem "nested_scaffold"
	gem "nifty-generators"
end

group :development do
  gem "kaltura"
  gem "kaltura-ruby"
  gem "mongrel", ">= 1.2.0.pre2"
  gem "chronic"
  gem "admin_view"
end

group :test do
  gem "factory_girl_rails"
  gem "cucumber-rails", :require => false
  gem "database_cleaner"
  gem "selenium-webdriver", "~> 2.18.0"
  gem "capybara"
  gem "shoulda"
  gem "email_spec"
end

group :production do
  gem "thin"
#	gem "pg", :require => "pg"
end

gem "mocha", :group => :test
