common: &common
  adapter: sqlite3
  username: micronemez_dbuser
  password:  

development:
  <<: *common
  database: micronemez_development

test:
  <<: *common
  database: micronemez_test

production:
  <<: *common
  database: micronemez_production

