DEFAULTS: &DEFAULTS
  partner_id: 100
  administrator_secret: c4d9b86b4aa2e761e65a1fadff763713
  service_url: http://video.micronemez.com

development:
  <<: *DEFAULTS
  kaltura_env: development

test:
  <<: *DEFAULTS
  kaltura_env: test

production:
  <<: *DEFAULTS
  kaltura_env: production
