DEFAULTS: &DEFAULTS
  username: edwardsharp
  api_key: c4d9b86b4aa2e761e65a1fadff763713

development:
  <<: *DEFAULTS
  container: dev_mcrnmz

test:
  <<: *DEFAULTS
  container: test_avatars

production:
  <<: *DEFAULTS
  container: micronemez
