# Read about factories at http://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :kaltura_video do
      mediaId "MyString"
      mediaType "MyString"
      accessControlId "MyString"
      adminTags "MyString"
      categories "MyString"
      categoriesIds "MyString"
      conversionQuality "MyString"
      createdAt "MyString"
      creditUrl "MyString"
      creditUserName "MyString"
      dataUrl "MyString"
      description "MyString"
      downloadUrl "MyString"
      duration "MyString"
      durationType "MyString"
      endDate "MyString"
      flavorParamsIds "MyString"
      groupId "MyString"
      height "MyString"
      id "MyString"
      licenseType "MyString"
      mediaDate "MyString"
      mediaType "MyString"
      moderationCount "MyString"
      moderationStatus "MyString"
      msDuration "MyString"
      name "MyString"
      objectType "MyString"
      partnerData "MyString"
      partnerId "MyString"
      plays "MyString"
      rank "MyString"
      searchProviderId "MyString"
      searchProviderType "MyString"
      searchText "MyString"
      sourceType "MyString"
      startDate "MyString"
      status "MyString"
      tags "MyString"
      thumbnailUrl "MyString"
      totalRank "MyString"
      type ""
      updatedAt "MyString"
      userId "MyString"
      version "MyString"
      views "MyString"
      votes "MyString"
      width "MyString"
    end
end